version: '3.5'
services:
  api:
    image: kopernick/hhapp-api
    build:  
      context: ../../../
      dockerfile: packages/api/docker/api/Dockerfile.prod
    networks: 
      - backend
    ports:
      - 8300:3000
      - 9229:9229 # Node debug
    command: sh -c 'wait-on tcp:database:5432 && node packages/api/dist/src/main.js'
    restart: 'unless-stopped'
    env_file: '.env'

  frontend:
    image: kopernick/hhapp-frontend
    build:  
      context: ../../../
      dockerfile: packages/api/docker/frontend/Dockerfile.prod
    networks: 
      - backend
    ports:
      - 80:3000
    command: sh -c 'npm start'
    restart: 'unless-stopped'
    environment: 
      - BASE_URL=http://householdapp.pl:3000
      - NODE_ENV=production
    env_file: '.env'

  mqtt-broker:
    image: eclipse-mosquitto:2
    networks: 
      - backend
    volumes: 
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-broker-data:/mosquitto/data
      - mqtt-broker-log:/mosquitto/log
    restart: 'unless-stopped'
    ports:
      - 1883:1883
      - 9001:9001


  database:
    image: postgres:13-alpine
    restart: 'unless-stopped'
    networks: 
      - backend
    volumes:
      - 'database:/var/lib/postgresql/data'
    env_file: '.env'
    ports:
      - '5432'

networks: 
  backend:
    attachable: true

volumes:
  database:
  mqtt-broker-data:
  mqtt-broker-log: