version: '3.7'
services:
  api:
    image: kopernick/hhapp-api
    build:  
      context: ..
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8300:3000
      - 9229:9229 # Node debug
    volumes:
      - '..:/app'
    command: sh -c 'npx wait-on tcp:database:5432 && npm run start:debug'
    restart: 'unless-stopped'
    environment: 
      - DB_USERNAME=hhapp
      - DB_PASSWORD=p455word
      - DB_DATABASE=hhapp

  database:
    image: kopernick/hhapp-database
    build:
      context: ..
      dockerfile: ./docker/database/Dockerfile
    restart: 'unless-stopped'
    volumes:
      - 'database:/var/lib/postgresql/data'
    environment: 
      - POSTGRES_PASSWORD=p455word
    ports:
      - '5432'

  database-admin:
    image: dpage/pgadmin4
    ports:
      - "8301:8111"
    volumes:
      - "${PWD}/docker/database/servers.json:/pgadmin4/servers.json"
    environment:
      - PGADMIN_DEFAULT_EMAIL=xd@xd.pl
      - PGADMIN_LISTEN_PORT=8111
      - PGADMIN_DEFAULT_PASSWORD=p455word
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    restart: unless-stopped

volumes:
  database: